# Generated by Django 3.2.9 on 2022-01-18 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeGenreRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Animes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='アニメ名')),
                ('type', models.CharField(max_length=30, verbose_name='タイプ')),
                ('rating', models.FloatField(verbose_name='評価')),
                ('members', models.PositiveIntegerField(verbose_name='評価者数')),
            ],
        ),
        migrations.CreateModel(
            name='Rationgs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.PositiveIntegerField()),
                ('rating', models.FloatField(verbose_name='評価')),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='ジャンル名')),
                ('genres', models.ManyToManyField(through='animeapp.AnimeGenreRelation', to='animeapp.Animes')),
            ],
        ),
        migrations.CreateModel(
            name='favorites',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('favorites', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='animegenrerelation',
            name='anime_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animeapp.animes'),
        ),
        migrations.AddField(
            model_name='animegenrerelation',
            name='ganre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animeapp.genres'),
        ),
    ]
