# Generated by Django 3.2.9 on 2022-01-22 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animeapp', '0002_auto_20220118_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeFavoriteRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animeapp.anime')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='favorite',
        ),
        migrations.AddField(
            model_name='anime',
            name='favorites',
            field=models.ManyToManyField(through='animeapp.AnimeFavoriteRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
