# Generated by Django 3.2.9 on 2022-01-22 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animeapp', '0004_auto_20220122_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='name',
            new_name='anime_name',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='name',
            new_name='genre_name',
        ),
    ]
