# Generated by Django 3.2.9 on 2022-01-23 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animeapp', '0005_auto_20220122_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genres',
            new_name='genre',
        ),
    ]
